### ISSUE TITLE
Service Dead?

### ISSUE THREAD

**Issue by ylluminate** [asmaps/hopper.pw#27]
The website no longer seems accessible.  Is the free service dead now?

**Comment by asmaps** [comment]
Unfortunately yes. Read more here: http://asmaps.github.io/hopper-pages/

**Comment by ylluminate** [comment]
:'( I'm so sorry. What a great service you were rendering.

**Comment by n3storm** [comment]
what were those abuses and is there we can do from a code point view to avoid them?

thanks for your effort and project anyway.

**Comment by asmaps** [comment]
Actually not really. The problem is that people have viruses on their PC which makes them part of botnets, host malware, etc. If the .pw registry sees that this happens under a .pw domain they shutdown the domain  and you have to prove that you have removed the source (in this case blocked the user). That's a policy that is .pw specific and could be circumvented by getting a .com for example. But the second problem would persist: If there is malware hopper.pw lands on blacklists which causes e.g. virus scanners to block access to *.hopper.pw sites. So you constantly have to get rid of blacklist entries and find users that "host" malware. I don't see a solution "in code" for that.

**Comment by n3storm** [comment]
I see, problem is windows then hahaha.

Thanks.
